language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy2.7-6.0"
  - "pypy3.5-6.0"
dist: xenial
install:
  - "pip install ."
  - "pip install -e .[google]"
  - "pip install ujson warcio"
  - "pip install rapidjson || true"
# command to run tests
script: python -m unittest discover -v
sudo: false
